import fs from 'node:fs'; import path from 'node:path'; import dotenv from 'dotenv'; import { fileURLToPath } from 'node:url'; import { pool, q } from './db.js'; import { hashPassword } from './auth.js';
dotenv.config();
const here=path.dirname(fileURLToPath(import.meta.url));
const schema=fs.readFileSync(path.join(here,'../sql/schema.sql'),'utf8');
await q(schema);
const username=process.env.ADMIN_USERNAME||'admin'; const password=process.env.ADMIN_PASSWORD;
if(!password) throw new Error('ADMIN_PASSWORD is required');
const hash=await hashPassword(password);
await q(`INSERT INTO users(username,password_hash,role) VALUES($1,$2,'admin') ON CONFLICT(username) DO UPDATE SET password_hash=EXCLUDED.password_hash, active=true, updated_at=NOW()`,[username,hash]);
await q(`INSERT INTO site_settings(id,data) VALUES(1,$1) ON CONFLICT(id) DO UPDATE SET data=site_settings.data || EXCLUDED.data,updated_at=NOW()`,[JSON.stringify({heroTitle:'Transforming Ideas Into Digital Excellence',heroText:'Diamond Tech builds modern websites, custom software, mobile applications and digital experiences designed to help businesses grow.',heroEyebrow:'SOFTWARE • WEB • MOBILE • DESIGN',heroImage:'/media/diamond-tech-logo.png',aboutTitle:'Building Technology That Moves Businesses Forward',aboutText:'Diamond Tech is a technology and digital solutions company focused on building practical, modern and professional digital products for businesses, organizations and institutions.',founderName:'Prince Diamond',founderTitle:'CEO & Founder, Diamond Tech',founderBio:'Prince Diamond is the founder of Diamond Tech, a technology company focused on turning ideas into practical digital products. His work brings together software engineering, design and business-focused technology.',founderImage:'/media/prince-diamond-founder.jpg',founderMessage:'We believe technology should make work simpler, businesses stronger and ideas easier to bring to life.',ctaTitle:"Have An Idea? Let's Build It.",ctaText:'From websites and software to mobile applications and professional digital design, Diamond Tech can turn your idea into a practical digital solution.',phone:'0756761076',email:'Diamondtech2233@gmail.com',siteTitle:'Diamond Tech | Software, Websites, Mobile Apps & Digital Solutions',metaDescription:'Diamond Tech builds professional websites, custom software, mobile applications, graphic designs, branding and digital solutions for businesses and organizations.'})]);
const services=[['Website Development','Modern, responsive and high-performance websites for businesses, schools, organizations and brands.','globe',['Responsive UI/UX','SEO-ready structure','Performance optimization']],['Custom Software','Business management systems, school systems, desktop applications and custom software solutions.','code',['Custom workflows','Secure data','Scalable architecture']],['Mobile Applications','Modern mobile applications with excellent user experiences and practical business functionality.','mobile',['Cross-platform apps','Modern interfaces','API integration']],['Graphic Design','Professional posters, flyers, social graphics, advertisements and digital designs.','palette',['Campaign graphics','Digital artwork','Marketing materials']],['Branding','Logo design, brand identity, visual systems and professional brand materials.','sparkles',['Logo systems','Brand guidelines','Visual identity']],['Digital Solutions','Technology solutions tailored to specific business and organizational requirements.','zap',['Digital transformation','Automation','Custom platforms']]];
for(let i=0;i<services.length;i++){const [title,description,icon,features]=services[i] as any;await q(`INSERT INTO services(title,slug,description,icon,image_url,features,sort_order,published) VALUES($1,$2,$3,$4,$5,$6,$7,true) ON CONFLICT(slug) DO NOTHING`,[title,(title as string).toLowerCase().replace(/[^a-z0-9]+/g,'-'),description,icon,'/media/diamond-tech-logo.png',JSON.stringify(features),i]);}
console.log('Database initialized and admin account prepared.'); await pool.end();
