import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import multer from 'multer'; import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import dotenv from 'dotenv';
import { fileURLToPath } from 'node:url'; import { q } from './db.js'; import { requireAuth, verifyPassword, tokenFor, audit } from './auth.js';
import { z } from 'zod';
dotenv.config();
const app=express(); const port=Number(process.env.PORT||5080); const origin=process.env.PUBLIC_ORIGIN||'http://localhost:5173';
const here=path.dirname(fileURLToPath(import.meta.url)); const uploadDir=path.resolve(process.env.UPLOAD_DIR||path.join(here,'../../uploads')); fs.mkdirSync(uploadDir,{recursive:true});
app.set('trust proxy',1); app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}})); app.use(cors({origin:origin==='*'?true:origin})); app.use(express.json({limit:'2mb'}));
app.use('/api/auth/login',rateLimit({windowMs:15*60*1000,max:10,standardHeaders:true,legacyHeaders:false}));
app.use('/uploads',express.static(uploadDir,{maxAge:'7d',immutable:true}));
const allowed=new Set(['image/jpeg','image/png','image/webp','image/avif','image/svg+xml','video/mp4','video/webm','video/quicktime','application/pdf']);
const storage=multer.diskStorage({destination:uploadDir,filename:(_r,f,cb)=>cb(null,crypto.randomUUID()+path.extname(f.originalname).toLowerCase())});
const upload=multer({storage,limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||50)*1024*1024},fileFilter:(_r,f,cb)=>cb(null,allowed.has(f.mimetype))});
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString(36);
app.get('/api/health',async(_req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'diamond-tech-cms-api'})}catch{res.status(503).json({ok:false})}});
app.get('/api/site',async(_req,res)=>{try{
 const [settings,services,projects,testimonials,blog,media]=await Promise.all([
 q('SELECT data FROM site_settings WHERE id=1'),q('SELECT * FROM services WHERE published=true ORDER BY sort_order,title'),q('SELECT * FROM projects WHERE published=true ORDER BY sort_order,title'),q('SELECT * FROM testimonials WHERE published=true ORDER BY sort_order,created_at DESC'),q('SELECT * FROM blog_posts WHERE published=true ORDER BY published_at DESC NULLS LAST,created_at DESC'),q(`SELECT id,original_name AS name,mime_type AS "mimeType",url,media_type AS "mediaType",page,section,caption,alt_text AS "altText",created_at AS "createdAt" FROM media WHERE published=true ORDER BY created_at DESC`)
 ]); res.json({settings:settings.rows[0]?.data||{},services:services.rows,projects:projects.rows,testimonials:testimonials.rows,blog:blog.rows,media:media.rows});
}catch(e){res.status(500).json({error:'Unable to load website data'})}});
app.post('/api/messages',async(req,res)=>{const s=z.object({fullName:z.string().min(2).max(120),email:z.string().email().max(200),phone:z.string().max(40).optional().default(''),service:z.string().max(100).optional().default(''),budget:z.string().max(100).optional().default(''),message:z.string().min(5).max(5000)}); const p=s.safeParse(req.body); if(!p.success)return res.status(400).json({error:'Please check the form fields'}); const x=p.data; const r=await q('INSERT INTO messages(full_name,email,phone,service,budget,message) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,created_at',[x.fullName,x.email,x.phone,x.service,x.budget,x.message]); res.status(201).json({ok:true,id:r.rows[0].id});});
app.post('/api/auth/login',async(req,res)=>{const p=z.object({username:z.string().min(1).max(80),password:z.string().min(1).max(200)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Username and password are required'});const r=await q('SELECT id,username,password_hash,role FROM users WHERE username=$1 AND active=true',[p.data.username]);if(!r.rows[0]||!(await verifyPassword(p.data.password,r.rows[0].password_hash)))return res.status(401).json({error:'Invalid username or password'});const u=r.rows[0];res.json({token:tokenFor(u),user:{id:u.id,username:u.username,role:u.role}})});
app.get('/api/admin/me',requireAuth,(req,res)=>res.json({user:(req as any).user}));
app.get('/api/admin/dashboard',requireAuth,async(_req,res)=>{const counts=await q(`SELECT (SELECT count(*) FROM services) services,(SELECT count(*) FROM projects) projects,(SELECT count(*) FROM testimonials) testimonials,(SELECT count(*) FROM media) media,(SELECT count(*) FROM blog_posts) blog,(SELECT count(*) FROM messages WHERE status='new') new_messages`);res.json(counts.rows[0]);});
app.put('/api/admin/settings',requireAuth,async(req,res)=>{const p=z.record(z.any()).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid settings'});await q(`INSERT INTO site_settings(id,data) VALUES(1,$1) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()`,[JSON.stringify(p.data)]);await audit(req,'update','settings','1');res.json({ok:true,data:p.data});});
app.get('/api/admin/revisions',requireAuth,async(_req,res)=>res.json((await q('SELECT id,label,created_at FROM site_revisions ORDER BY created_at DESC LIMIT 50')).rows));
app.post('/api/admin/revisions',requireAuth,async(req,res)=>{const p=z.object({label:z.string().min(1).max(180),data:z.record(z.any())}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid revision'});const r=await q('INSERT INTO site_revisions(label,data,created_by) VALUES($1,$2,$3) RETURNING id,label,created_at',[p.data.label,JSON.stringify(p.data.data),(req as any).user.sub]);await audit(req,'create','revision',r.rows[0].id,{label:p.data.label});res.status(201).json(r.rows[0]);});
app.post('/api/admin/revisions/:id/restore',requireAuth,async(req,res)=>{const r=await q('SELECT data FROM site_revisions WHERE id=$1',[(req.params.id as string)]);if(!r.rows[0])return res.status(404).json({error:'Revision not found'});const data=r.rows[0].data;await q(`INSERT INTO site_settings(id,data) VALUES(1,$1) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()`,[JSON.stringify(data)]);await audit(req,'restore','revision',(req.params.id as string));res.json({settings:data,services:(await q('SELECT * FROM services WHERE published=true ORDER BY sort_order,title')).rows,projects:(await q('SELECT * FROM projects WHERE published=true ORDER BY sort_order,title')).rows,testimonials:(await q('SELECT * FROM testimonials WHERE published=true ORDER BY sort_order,created_at DESC')).rows,blog:(await q('SELECT * FROM blog_posts WHERE published=true ORDER BY published_at DESC NULLS LAST,created_at DESC')).rows,media:(await q(`SELECT id,original_name AS name,mime_type AS "mimeType",url,media_type AS "mediaType",page,section,caption,alt_text AS "altText",created_at AS "createdAt" FROM media WHERE published=true ORDER BY created_at DESC`)).rows});});
const serviceSchema=z.object({title:z.string().min(2).max(120),description:z.string().max(2000),icon:z.string().max(40).default('code'),imageUrl:z.string().max(1000).nullable().optional(),features:z.array(z.string().max(200)).max(20).default([]),sortOrder:z.number().int().default(0),published:z.boolean().default(false)});
app.get('/api/admin/services',requireAuth,async(_r,res)=>res.json((await q('SELECT * FROM services ORDER BY sort_order,title')).rows));
app.post('/api/admin/services',requireAuth,async(req,res)=>{const p=serviceSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid service'});const x=p.data;const r=await q(`INSERT INTO services(title,slug,description,icon,image_url,features,sort_order,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[x.title,slugify(x.title),x.description,x.icon,x.imageUrl||null,JSON.stringify(x.features),x.sortOrder,x.published]);await audit(req,'create','service',r.rows[0].id);res.status(201).json(r.rows[0]);});
app.put('/api/admin/services/:id',requireAuth,async(req,res)=>{const p=serviceSchema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid service'});const x=p.data;const r=await q(`UPDATE services SET title=COALESCE($1,title),description=COALESCE($2,description),icon=COALESCE($3,icon),image_url=COALESCE($4,image_url),features=COALESCE($5,features),sort_order=COALESCE($6,sort_order),published=COALESCE($7,published),updated_at=NOW() WHERE id=$8 RETURNING *`,[x.title??null,x.description??null,x.icon??null,x.imageUrl??null,x.features?JSON.stringify(x.features):null,x.sortOrder??null,x.published??null,(req.params.id as string)]);if(!r.rows[0])return res.status(404).json({error:'Service not found'});await audit(req,'update','service',(req.params.id as string));res.json(r.rows[0]);});
app.delete('/api/admin/services/:id',requireAuth,async(req,res)=>{await q('DELETE FROM services WHERE id=$1',[(req.params.id as string)]);await audit(req,'delete','service',(req.params.id as string));res.status(204).end()});
const simpleSchema=z.object({name:z.string().min(2).max(120),company:z.string().max(160).default(''),text:z.string().min(2).max(2000),imageUrl:z.string().max(1000).nullable().optional(),published:z.boolean().default(false),sortOrder:z.number().int().default(0)});
app.get('/api/admin/testimonials',requireAuth,async(_r,res)=>res.json((await q('SELECT * FROM testimonials ORDER BY sort_order,created_at DESC')).rows));
app.post('/api/admin/testimonials',requireAuth,async(req,res)=>{const p=simpleSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid testimonial'});const x=p.data;const r=await q('INSERT INTO testimonials(name,company,text,image_url,published,sort_order) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[x.name,x.company,x.text,x.imageUrl||null,x.published,x.sortOrder]);await audit(req,'create','testimonial',r.rows[0].id);res.status(201).json(r.rows[0]);});
app.put('/api/admin/testimonials/:id',requireAuth,async(req,res)=>{const p=simpleSchema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid testimonial'});const x=p.data;const r=await q('UPDATE testimonials SET name=COALESCE($1,name),company=COALESCE($2,company),text=COALESCE($3,text),image_url=COALESCE($4,image_url),published=COALESCE($5,published),sort_order=COALESCE($6,sort_order),updated_at=NOW() WHERE id=$7 RETURNING *',[x.name??null,x.company??null,x.text??null,x.imageUrl??null,x.published??null,x.sortOrder??null,(req.params.id as string)]);if(!r.rows[0])return res.status(404).json({error:'Not found'});await audit(req,'update','testimonial',(req.params.id as string));res.json(r.rows[0]);});
app.delete('/api/admin/testimonials/:id',requireAuth,async(req,res)=>{await q('DELETE FROM testimonials WHERE id=$1',[(req.params.id as string)]);await audit(req,'delete','testimonial',(req.params.id as string));res.status(204).end()});
app.get('/api/admin/media',requireAuth,async(_r,res)=>res.json((await q(`SELECT id,original_name AS name,mime_type AS "mimeType",url,media_type AS "mediaType",page,section,caption,alt_text AS "altText",published,created_at AS "createdAt" FROM media ORDER BY created_at DESC`)).rows));
app.post('/api/admin/media',requireAuth,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Choose a file'});const page=String(req.body.page||'Home'),section=String(req.body.section||'Hero'),caption=String(req.body.caption||'').slice(0,500),alt=String(req.body.altText||'').slice(0,300);const type=req.file.mimetype.startsWith('image/')?'image':req.file.mimetype.startsWith('video/')?'video':'file';const url=`/uploads/${req.file.filename}`;const r=await q(`INSERT INTO media(filename,original_name,mime_type,size_bytes,url,media_type,page,section,caption,alt_text,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,original_name AS name,mime_type AS "mimeType",url,media_type AS "mediaType",page,section,caption,alt_text AS "altText",published,created_at AS "createdAt"`,[req.file.filename,req.file.originalname,req.file.mimetype,req.file.size,url,type,page,section,caption,alt,(req as any).user.sub]);await audit(req,'upload','media',r.rows[0].id,{page,section});res.status(201).json(r.rows[0]);}catch(e){if(req.file)fs.rmSync(path.join(uploadDir,req.file.filename),{force:true});res.status(400).json({error:'Upload failed. Check the file type and size.'})}});
app.put('/api/admin/media/:id',requireAuth,async(req,res)=>{const p=z.object({page:z.string().max(80).optional(),section:z.string().max(120).optional(),caption:z.string().max(500).optional(),altText:z.string().max(300).optional(),published:z.boolean().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid media update'});const x=p.data;const r=await q(`UPDATE media SET page=COALESCE($1,page),section=COALESCE($2,section),caption=COALESCE($3,caption),alt_text=COALESCE($4,alt_text),published=COALESCE($5,published) WHERE id=$6 RETURNING id,original_name AS name,url,media_type AS "mediaType",page,section,caption,alt_text AS "altText",published,created_at AS "createdAt"`,[x.page??null,x.section??null,x.caption??null,x.altText??null,x.published??null,(req.params.id as string)]);if(!r.rows[0])return res.status(404).json({error:'Media not found'});await audit(req,'update','media',(req.params.id as string));res.json(r.rows[0]);});
app.delete('/api/admin/media/:id',requireAuth,async(req,res)=>{const r=await q('DELETE FROM media WHERE id=$1 RETURNING filename',[(req.params.id as string)]);if(r.rows[0])fs.rmSync(path.join(uploadDir,r.rows[0].filename),{force:true});await audit(req,'delete','media',(req.params.id as string));res.status(204).end()});

const projectSchema=z.object({title:z.string().min(2).max(160),category:z.string().max(80).default('Software'),description:z.string().max(2000).default(''),content:z.string().max(12000).default(''),coverUrl:z.string().max(1000).nullable().optional(),gallery:z.array(z.string().max(1000)).max(50).default([]),technologies:z.array(z.string().max(80)).max(30).default([]),published:z.boolean().default(false),sortOrder:z.number().int().default(0)});
app.get('/api/admin/projects',requireAuth,async(_r,res)=>res.json((await q('SELECT * FROM projects ORDER BY sort_order,title')).rows));
app.post('/api/admin/projects',requireAuth,async(req,res)=>{const p=projectSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid project'});const x=p.data;const r=await q(`INSERT INTO projects(title,slug,category,description,content,cover_url,gallery,technologies,published,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[x.title,slugify(x.title),x.category,x.description,x.content,x.coverUrl||null,JSON.stringify(x.gallery),JSON.stringify(x.technologies),x.published,x.sortOrder]);await audit(req,'create','project',r.rows[0].id);res.status(201).json(r.rows[0]);});
app.put('/api/admin/projects/:id',requireAuth,async(req,res)=>{const p=projectSchema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid project'});const x=p.data;const r=await q(`UPDATE projects SET title=COALESCE($1,title),category=COALESCE($2,category),description=COALESCE($3,description),content=COALESCE($4,content),cover_url=COALESCE($5,cover_url),gallery=COALESCE($6,gallery),technologies=COALESCE($7,technologies),published=COALESCE($8,published),sort_order=COALESCE($9,sort_order),updated_at=NOW() WHERE id=$10 RETURNING *`,[x.title??null,x.category??null,x.description??null,x.content??null,x.coverUrl??null,x.gallery?JSON.stringify(x.gallery):null,x.technologies?JSON.stringify(x.technologies):null,x.published??null,x.sortOrder??null,(req.params.id as string)]);if(!r.rows[0])return res.status(404).json({error:'Project not found'});await audit(req,'update','project',(req.params.id as string));res.json(r.rows[0]);});
app.delete('/api/admin/projects/:id',requireAuth,async(req,res)=>{await q('DELETE FROM projects WHERE id=$1',[(req.params.id as string)]);await audit(req,'delete','project',(req.params.id as string));res.status(204).end()});
const blogSchema=z.object({title:z.string().min(2).max(180),excerpt:z.string().max(1000).default(''),content:z.string().max(20000).default(''),coverUrl:z.string().max(1000).nullable().optional(),author:z.string().max(120).default('Diamond Tech'),tags:z.array(z.string().max(60)).max(20).default([]),seo:z.record(z.any()).default({}),published:z.boolean().default(false)});
app.get('/api/admin/blog',requireAuth,async(_r,res)=>res.json((await q('SELECT * FROM blog_posts ORDER BY created_at DESC')).rows));
app.post('/api/admin/blog',requireAuth,async(req,res)=>{const p=blogSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid article'});const x=p.data;const r=await q(`INSERT INTO blog_posts(title,slug,excerpt,content,cover_url,author,tags,seo,published,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,CASE WHEN $9 THEN NOW() ELSE NULL END) RETURNING *`,[x.title,slugify(x.title),x.excerpt,x.content,x.coverUrl||null,x.author,JSON.stringify(x.tags),JSON.stringify(x.seo),x.published]);await audit(req,'create','blog_post',r.rows[0].id);res.status(201).json(r.rows[0]);});
app.put('/api/admin/blog/:id',requireAuth,async(req,res)=>{const p=blogSchema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid article'});const x=p.data;const r=await q(`UPDATE blog_posts SET title=COALESCE($1,title),excerpt=COALESCE($2,excerpt),content=COALESCE($3,content),cover_url=COALESCE($4,cover_url),author=COALESCE($5,author),tags=COALESCE($6,tags),seo=COALESCE($7,seo),published=COALESCE($8,published),published_at=CASE WHEN $8=true AND published_at IS NULL THEN NOW() WHEN $8=false THEN NULL ELSE published_at END,updated_at=NOW() WHERE id=$9 RETURNING *`,[x.title??null,x.excerpt??null,x.content??null,x.coverUrl??null,x.author??null,x.tags?JSON.stringify(x.tags):null,x.seo?JSON.stringify(x.seo):null,x.published??null,(req.params.id as string)]);if(!r.rows[0])return res.status(404).json({error:'Article not found'});await audit(req,'update','blog_post',(req.params.id as string));res.json(r.rows[0]);});
app.delete('/api/admin/blog/:id',requireAuth,async(req,res)=>{await q('DELETE FROM blog_posts WHERE id=$1',[(req.params.id as string)]);await audit(req,'delete','blog_post',(req.params.id as string));res.status(204).end()});
app.get('/api/admin/messages',requireAuth,async(_r,res)=>res.json((await q('SELECT * FROM messages ORDER BY created_at DESC')).rows));
app.patch('/api/admin/messages/:id',requireAuth,async(req,res)=>{const p=z.object({status:z.enum(['new','read','replied','archived'])}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid status'});const r=await q('UPDATE messages SET status=$1,read_at=CASE WHEN $1<>\'new\' THEN COALESCE(read_at,NOW()) ELSE NULL END WHERE id=$2 RETURNING *',[p.data.status,(req.params.id as string)]);if(!r.rows[0])return res.status(404).json({error:'Message not found'});await audit(req,'update','message',(req.params.id as string),{status:p.data.status});res.json(r.rows[0]);});
app.get('/api/admin/audit',requireAuth,async(_r,res)=>res.json((await q('SELECT a.*,u.username FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 250')).rows));
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(500).json({error:'Server error'});});
app.listen(port,()=>console.log(`Diamond Tech CMS API running on http://127.0.0.1:${port}`));

